site_name: Learn with Antura
site_url: https://antura.org
site_author: VGWB
site_description: The Learn with Antura project website and docs for Educators, Designers and Game Developers
copyright: <a href="/about">© VGWB | CC BY-NC-SA</a> | <a href="/privacy-policy">Privacy Policy</a>

theme:
  name: material
  language: en
  custom_dir: docs/assets/override
  logo: assets/icon.png
  favicon: assets/icon.png
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/file-edit-outline
  features:
    - content.action.edit
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
#    - navigation.expand
#    - navigation.sections
    - announce.dismiss
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated

markdown_extensions:
  - tables
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - def_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Plugins
plugins:
  - search:
      lang: en
  - table-reader
  - minify:
      minify_html: true
  - awesome-pages
  - exclude:
      glob:
        - "*/_local/*"
        - "*/_draft/*"
  - awesome-nav
  - tags:
      tags: true
  - blog:
      blog_toc: true
      authors: false
      post_date_format: "dd-MM-yyyy"
      post_url_date_format: yyyy
      post_url_format: "{date}/{slug}"
      post_readtime: false

repo_url: https://github.com/vgwb/Antura
edit_uri: "edit/main/docs/"
repo_name: GitHub/Antura

# extra:
#   alternate:
#     - name: English
#       link: / 
#       lang: en
#     - name: Deutsch
#       link: /de/
#       lang: de

extra_javascript:
#  - assets/yarn/yarn-graph.js
  - assets/yarn/yarn-script.js
extra_css:
  - assets/stylesheets/extra.css
#  - assets/yarn/yarn-graph.css
  - assets/yarn/yarn-script.css

#not_in_nav: |
#  /discover/quest/*.md
#
## Page tree
#nav:
#  - Home: index.md
#  - Blog: 
#      - blog/index.md
#  - Manual:
#      - manual/index.md
#      - How to Install and Setup: manual/install.md
#      - Learn Languages: manual/learnlanguage_module.md
#      - Discover Europe:
#        - Introduction: manual/discover_introduction.md
#        - Features: manual/discover_module.md
#        - How to play quests: manual/discover_how_to_play.md
#      - Classroom Guide: manual/classroom_guide.md
#      - Feedback and Support: manual/support.md
#      - FAQ: manual/faq.md
#      - Changelog: manual/changelog.md
#  - Discover:
#      - discover/index.md
#      - Quests: discover/quest/index.md
#      - Topics: discover/topics/index.md
#      - Cards: discover/cards/index.md
#      - Words: discover/words/index.md
#      - Activities: discover/activities/index.md
#      - Locations: discover/locations/index.md
#  - About:
#      - Learn with Antura: about/index.md
#      - The Team: about/team.md
#      - VGWB: about/vgwb.md
#      - Privacy Policy: about/privacy-policy.md
#  - Forum: https://antura.discourse.group

