//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace Antura.Database
{
    public enum LetterDataSunMoon
    {
        None = 0,
        Moon = 1,
        Sun = 2,
    }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
