//-------START OF AUTOGENERATED FILE - DO NOT EDIT------

namespace Antura.Database
{
    public enum WordDataArticle
    {
        None = 0,
        Determinative = 1,
    }
}

////-------END OF AUTOGENERATED FILE - DO NOT EDIT------
